;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                  Consant.INC                               ;
;                            Parsing Serial Functions                        ;
;                                 Include File                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains the definitions for the parsing serial functions(parse.ASM).
;
; Revision History:
; 12/08/2012 Yuqi Zhu  Initial Revision
; 12/12/2012 Yuqi Zhu  Updated Comments

NSignASCII         EQU 45
PSignASCII         EQU 43
POS_SIGN           EQU  1           ;Positve Sign
NEG_SIGN           EQU  -1          ;Negative Sign
TWOPI              EQU  360         ;Degree of twopi