;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                 Converts.INC                               ;
;                                Convert Routine                             ;
;                                 Include File                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains the definitions for the convert functions(converts.ASM).
;
; Revision History:
;   12/15/2012 Yuqi Zhu Updates Comments


ASCIIDigitConvert EQU 48
ASCIICharacterConvert EQU 55
