
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                              Mainloopkeypad.INC                            ;
;                                Keypad Routine                              ;
;                                 Include File                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains the definitions for the Mainloopkeypad (mainloopkeypad.ASM).
;
; Revision History:
;    3/31/2013 Yuqi Zhu Initial Revision
; General Definitions:
MAXIMUM_LENGTH    EQU 8   ; The maximum length for the buffer

